version: '2'

services:
  bokeh:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: ["/opt/serve-app.sh"]
    environment:
      BOKEH_PREFIX: /judit
      EXPLORE_URL: "https://dev-www.materialscloud.org/explore/judit" 
    volumes:
     - '/tmp:/app/.aiida/repository/judit'
    ports:
      - '5006:5006'
