version: '2'

services:
  bokeh:
    image: judit_discover_section
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
    volumes:
      - '/Local/ruess/.aiida/repository/judit-test/:/app/.aiida/repository/judit/'
    ports:
      - '5006:5006'
      - '5432:5432'
