version: '2'

services:
  bokeh:
    image: judit_discover_section
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      #- '/Users/ruess/sourcecodes/aiida/JuDiT_webinterface/venv/.aiida/repository/judit:/app/.aiida/repository/judit/'
      - '/Local/ruess/.aiida/repository/judit-test/:/app/.aiida/repository/judit/'
    ports:
      - "5006:5006"
